package com.example.perfchecker;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * ThresholdChecker validates JMeter performance test results against defined thresholds.
 *
 * Reads statistics.json generated by JMeter and checks the "Total" transaction metrics.
 * Exits with code 0 if all thresholds pass, 1 if any threshold is violated.
 *
 * Thresholds are loaded with the following priority order:
 * 1. Properties file (if specified as second argument)
 * 2. Environment variables (for backward compatibility)
 * 3. Hardcoded defaults
 *
 * Properties file keys:
 * - perf.max.median.response.time (default: 1000ms)
 * - perf.max.error.rate (default: 1.0%)
 * - perf.min.throughput (default: 25.0 req/sec)
 * - perf.max.p90.response.time (default: 3300ms)
 *
 * Environment variables (legacy support):
 * - PERF_MAX_MEDIAN_RESPONSE_TIME
 * - PERF_MAX_ERROR_RATE
 * - PERF_MIN_THROUGHPUT
 * - PERF_MAX_P90_RESPONSE_TIME
 *
 * Usage: java -jar threshold-checker.jar <path-to-statistics.json> [path-to-thresholds.properties]
 */
public class ThresholdChecker {

    // Default thresholds (can be overridden by environment variables)
    private static final double DEFAULT_MAX_MEDIAN_RESPONSE_TIME = 1000.0;
    private static final double DEFAULT_MAX_ERROR_RATE = 1.0;
    private static final double DEFAULT_MIN_THROUGHPUT = 25.0;
    private static final double DEFAULT_MAX_P90_RESPONSE_TIME = 3300.0;

    // Actual thresholds (read from env or use defaults)
    private static double maxMedianResponseTime;
    private static double maxErrorRate;
    private static double minThroughput;
    private static double maxP90ResponseTime;

    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("Usage: java -jar threshold-checker.jar <path-to-statistics.json> [path-to-thresholds.properties]");
            System.exit(2);
        }

        String statisticsFile = args[0];
        String propertiesFile = args.length > 1 ? args[1] : null;

        // Load thresholds from properties file, environment variables, or use defaults
        loadThresholds(propertiesFile);

        try {
            // Parse statistics.json
            Gson gson = new Gson();
            FileReader reader = new FileReader(statisticsFile);
            JsonObject root = gson.fromJson(reader, JsonObject.class);
            reader.close();

            // Extract "Total" transaction metrics
            JsonObject total = root.getAsJsonObject("Total");
            if (total == null) {
                System.err.println("ERROR: 'Total' transaction not found in statistics.json");
                System.exit(2);
            }

            double medianResTime = total.get("medianResTime").getAsDouble();
            double errorPct = total.get("errorPct").getAsDouble();
            double throughput = total.get("throughput").getAsDouble();
            double pct1ResTime = total.get("pct1ResTime").getAsDouble(); // 90th percentile

            // Check thresholds
            List<String> violations = new ArrayList<>();

            System.out.println("\n========== Performance Threshold Check ==========");
            System.out.println("Configuration:");
            System.out.println("  Max Median Response Time: " + maxMedianResponseTime + "ms");
            System.out.println("  Max Error Rate: " + maxErrorRate + "%");
            System.out.println("  Min Throughput: " + minThroughput + " req/sec");
            System.out.println("  Max P90 Response Time: " + maxP90ResponseTime + "ms");
            System.out.println("\nResults:");

            // Check error rate
            if (errorPct <= maxErrorRate) {
                System.out.println("✓ Error rate: " + String.format("%.2f", errorPct) +
                                 "% (threshold: " + maxErrorRate + "%)");
            } else {
                String violation = String.format("Error rate: %.2f%% (threshold: %.1f%%) - EXCEEDED by %.0f%%",
                    errorPct, maxErrorRate, ((errorPct / maxErrorRate) - 1) * 100);
                violations.add(violation);
                System.out.println("✗ " + violation);
            }

            // Check throughput
            if (throughput >= minThroughput) {
                System.out.println("✓ Throughput: " + String.format("%.2f", throughput) +
                                 " req/sec (threshold: " + minThroughput + " req/sec)");
            } else {
                String violation = String.format("Throughput: %.2f req/sec (threshold: %.1f req/sec) - BELOW by %.0f%%",
                    throughput, minThroughput, (1 - (throughput / minThroughput)) * 100);
                violations.add(violation);
                System.out.println("✗ " + violation);
            }

            // Check median response time
            if (medianResTime <= maxMedianResponseTime) {
                System.out.println("✓ Median response time: " + String.format("%.2f", medianResTime) +
                                 "ms (threshold: " + maxMedianResponseTime + "ms)");
            } else {
                String violation = String.format("Median response time: %.2fms (threshold: %.1fms) - EXCEEDED by %.0f%%",
                    medianResTime, maxMedianResponseTime, ((medianResTime / maxMedianResponseTime) - 1) * 100);
                violations.add(violation);
                System.out.println("✗ " + violation);
            }

            // Check 90th percentile response time
            if (pct1ResTime <= maxP90ResponseTime) {
                System.out.println("✓ P90 response time: " + String.format("%.2f", pct1ResTime) +
                                 "ms (threshold: " + maxP90ResponseTime + "ms)");
            } else {
                String violation = String.format("P90 response time: %.2fms (threshold: %.1fms) - EXCEEDED by %.0f%%",
                    pct1ResTime, maxP90ResponseTime, ((pct1ResTime / maxP90ResponseTime) - 1) * 100);
                violations.add(violation);
                System.out.println("✗ " + violation);
            }

            System.out.println("=================================================");

            // Report results
            if (violations.isEmpty()) {
                System.out.println("\n✅ All performance thresholds passed!");
                System.exit(0);
            } else {
                System.out.println("\n❌ Performance regression detected! " + violations.size() + " threshold(s) violated:");
                for (String violation : violations) {
                    System.out.println("  - " + violation);
                }
                System.exit(1);
            }

        } catch (IOException e) {
            System.err.println("ERROR: Failed to read statistics file: " + e.getMessage());
            System.exit(2);
        } catch (Exception e) {
            System.err.println("ERROR: Failed to parse statistics: " + e.getMessage());
            System.exit(2);
        }
    }

    /**
     * Load thresholds with priority: properties file -> environment variables -> defaults
     */
    private static void loadThresholds(String propertiesFile) {
        // Start with defaults
        maxMedianResponseTime = DEFAULT_MAX_MEDIAN_RESPONSE_TIME;
        maxErrorRate = DEFAULT_MAX_ERROR_RATE;
        minThroughput = DEFAULT_MIN_THROUGHPUT;
        maxP90ResponseTime = DEFAULT_MAX_P90_RESPONSE_TIME;

        // Override with environment variables if set
        maxMedianResponseTime = getEnvDouble("PERF_MAX_MEDIAN_RESPONSE_TIME", maxMedianResponseTime);
        maxErrorRate = getEnvDouble("PERF_MAX_ERROR_RATE", maxErrorRate);
        minThroughput = getEnvDouble("PERF_MIN_THROUGHPUT", minThroughput);
        maxP90ResponseTime = getEnvDouble("PERF_MAX_P90_RESPONSE_TIME", maxP90ResponseTime);

        // Override with properties file if provided
        if (propertiesFile != null) {
            loadFromProperties(propertiesFile);
        }
    }

    /**
     * Load thresholds from properties file
     */
    private static void loadFromProperties(String propertiesFile) {
        try (FileInputStream fis = new FileInputStream(propertiesFile)) {
            Properties props = new Properties();
            props.load(fis);

            maxMedianResponseTime = getPropertyDouble(props, "perf.max.median.response.time", maxMedianResponseTime);
            maxErrorRate = getPropertyDouble(props, "perf.max.error.rate", maxErrorRate);
            minThroughput = getPropertyDouble(props, "perf.min.throughput", minThroughput);
            maxP90ResponseTime = getPropertyDouble(props, "perf.max.p90.response.time", maxP90ResponseTime);

            System.out.println("Loaded thresholds from: " + propertiesFile);
        } catch (IOException e) {
            System.err.println("WARNING: Failed to load properties file '" + propertiesFile + "': " + e.getMessage());
            System.err.println("Using environment variables or defaults.");
        }
    }

    /**
     * Read double value from Properties with fallback to default
     */
    private static double getPropertyDouble(Properties props, String key, double defaultValue) {
        String value = props.getProperty(key);
        if (value != null && !value.trim().isEmpty()) {
            try {
                return Double.parseDouble(value.trim());
            } catch (NumberFormatException e) {
                System.err.println("WARNING: Invalid value for " + key + ": " + value +
                                 ". Using default: " + defaultValue);
                return defaultValue;
            }
        }
        return defaultValue;
    }

    /**
     * Read double value from environment variable with fallback to default
     */
    private static double getEnvDouble(String envVar, double defaultValue) {
        String value = System.getenv(envVar);
        if (value != null && !value.trim().isEmpty()) {
            try {
                return Double.parseDouble(value);
            } catch (NumberFormatException e) {
                System.err.println("WARNING: Invalid value for " + envVar + ": " + value +
                                 ". Using default: " + defaultValue);
                return defaultValue;
            }
        }
        return defaultValue;
    }
}
